options:
  logging: CLOUD_LOGGING_ONLY

steps:

# Step 1: Upload dags
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '-r', './dags/*', 'gs://europe-west2-football-data--c5cbc078-bucket/dags/']
  id: 'upload-dags'


# Step 2: Upload source code
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', '-r', './source/*', 'gs://source_code_yteklai91/']
  id: 'upload-source-code'

## Step 3: Deploy the Cloud Function
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud functions deploy fetch_and_store_data \
        --runtime python39 \
        --trigger-http \
        --allow-unauthenticated \
        --region europe-west2 \
        --entry-point fetch_and_store_data \
        --source ./source/cloud_function/

timeout: '1200s'
